# Generated by Django 6.1 on 2026-08-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
    ]
